(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



Needs["Madtomma`MadLanguage`MADinput`"]


Needs["Madtomma`Mfs`TrackTable`"]


Needs["Madtomma`Mfs`ColorListPlot`"]


Needs["Graphics`MultipleListPlot`"]


Needs["Madtomma`Imperf`ManageCases`"]


Needs["Madtomma`Dynap`dynaView`"]


newTfsFileName[]:=
	"track"<>ToString[1+Max[ToExpression[StringReplace[{"0"}\[Union]FileNames["track*.tfs"],{"track"->"",".tfs"->""}]]]
			]<>".tfs"


trackTemplate[tag_,opticsfile_,deltap_,damp_,initials_,turns_]:={
		MADcomment[trackDescription[tag]],
		MADtitle[trackDescription[tag]],
		"COGUESS,automatic=True",
		MADcall[opticsfile],
		"BEAM,particle=POSITRON,energy=EGeV,radiate",
		"EMIT,deltap="<>ToString[deltap],
		 "Beam,ex=1e-8 , ey=1e-8, et=1e-6",
		If[damp,"TRACK,DAMP","TRACK,-DAMP"],
		initials,
		MADrun[turns],
		"ENDTRACK",
		MADarchive[TRACK,trackTableFile[tag]]
	}


trackDescription[]:=trackDescription /@ domain[trackDescription]


trackTableFile[]:=trackTableFile /@ domain[trackTableFile]


showTrackDescription:=TableForm[
		{#,trackTableFile[#],trackDescription[#]}& /@ domain[trackDescription],
		TableHeadings->{None,{"tag","Track data","Description"}}
		]


doTracking[tag_]:=Module[{madfile="trackSpec.mad",echofile="trackSpec.echo"},
		bumpFile[madfile];
		bumpFile["print"];
		bumpFile[echofile];
		bumpFile[trackTableFile[tag]];
		makeMADfile["trackSpec.mad",trackSpec[tag]];
		Run["mad -new < " <> madfile <> " > " <> echofile];
		FileNames[trackTableFile[tag]]
		]


saveTrackDescription[filename_String]:=Block[{},
		bumpFile[filename];
		trackingDir=filename;
		Save[f,{trackDescription,trackTableFile,trackSpec}]
	]



