(***********************************************************************
This file was generated automatically by the Mathematica front end.
It contains Initialization cells from a Notebook file, which typically
will have the same name as this file except ending in ".nb" instead of
".m".

This file is intended to be loaded into the Mathematica kernel using
the package loading commands Get or Needs.  Doing so is equivalent to
using the Evaluate Initialization Cells menu command in the front end.

DO NOT EDIT THIS FILE.  This entire file is regenerated automatically 
each time the parent Notebook file is saved in the Mathematica front end.
Any changes you make to this file will be overwritten.
***********************************************************************)































































































BeginPackage["Madtomma`Mfs`EigenTable`",
	{"Madtomma`Mfs`Mfs`",
	"JMJUtils`BumpEtc`"}]





EigenTable::usage = "EigenTable.m is a package for working with EIGEN tables saved by MAD.";

makeEigenTable::usage = "makeEigenTable[mfsdata] transforms an mfs data object created from a MAD EIGEN table into a trackTable data object.";



makeEigenTable::badarg = "Wrong input mfs object.";







Begin["`Private`"]





protected =
    Unprotect[mfsTypes,mfsKeyValue,mfsKeyNames,mfsColumnNames,
      mfsInterpretKeys,mfsAddKey,mfsDeleteKey,mfsEditKey,mfsColumn];











orbtemplate = {"XC","PXC","YC","PYC","TC","PTC"};

eigtemplate=Table["E" <> ToString[j] <> ToString[i]  ,{i,1,6},{j,1,6}];

mutemplate={"MU1","MU2","MU3"};

orbpos[qpmfs_mfs]:=
    Flatten[(Position[
              mfsColumnNames[((StringReplace[#,{"CO"\[Rule]"C"}]&)/@
                    qpmfs)],#])&/@orbtemplate];

eigpos[qpmfs_mfs]:=
    Flatten[(Position[mfsColumnNames[qpmfs],#])&/@ Flatten[eigtemplate]];

mupos[qpmfs_mfs]:=Flatten[(Position[mfsColumnNames[qpmfs],#])&/@ mutemplate];





makeEigenTable[qpmfs_mfs]:=Module[{},
		If[mfsKeyValue[qpmfs,"TYPE"]=="EIGEN",
			(
				EigenTable[
						First[qpmfs],
					Join[
						Select[((StringReplace[#,{"CO"\[Rule]"C"}]&)/@
                    qpmfs\[LeftDoubleBracket]2\[RightDoubleBracket]),
							Not[
                    MemberQ[
                      Flatten[
                        eigtemplate\[Union] 
                          orbtemplate\[Union]mutemplate],#]]&
								],
						{"ORBIT","EIGENVECTORS","MU"}
						],
					({
					#\[LeftDoubleBracket]1\[RightDoubleBracket],
						#\[LeftDoubleBracket]2\[RightDoubleBracket],
						#\[LeftDoubleBracket]orbpos[qpmfs]\[RightDoubleBracket],
						Partition[#\[LeftDoubleBracket]eigpos[qpmfs]\[RightDoubleBracket],6],
						#\[LeftDoubleBracket]mupos[qpmfs]\[RightDoubleBracket]
									}&)/@Last[qpmfs]
						]
				),
			(Message[makeEigenTable::badarg];Null)
		]
		];





mfsTypes=Union[mfsTypes,{EigenTable}];



mfsKeyValue[qp_EigenTable,keyss_]:=mfsKeyValue[mfs @@ qp,keyss]

mfsKeyNames[qp_EigenTable]:=mfsKeyNames[mfs @@ qp]

mfsColumnNames[qp_EigenTable]:=mfsColumnNames[mfs@@qp]

mfsInterpretKeys[qp_EigenTable]:=mfsInterpretKeys[mfs @@ qp]

mfsAddKey[qp_EigenTable,{key_String,value_}]:=
	mfsAddKey[mfs @@ qp,{key,value}]

mfsDeleteKey[qp_EigenTable,key_String]:=mfsDeleteKey[mfs@@qp,key]

mfsEditKey[qp_EigenTable,{key_String,newValue_}]:=
  mfsEditKey[mfs@@qp,{key,newValue}]

mfsColumn[qp_EigenTable,key_String]:=
  Flatten[(#[[Flatten[Position[mfsColumnNames[qp],key]]]])& /@Last[qp],1]

mfsColumn[qp_EigenTable,keys_List]:= mfsColumn[qp,#]& /@ keys

mfsColumn[qp_EigenTable]:=Last[qp]



Protect[ Evaluate[protected] ];



End[ ]









Protect[makeEigenTable]





EndPackage[ ]



























































































































































































