(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



BeginPackage["Madtomma`Mfs`MAD8Survey`","Madtomma`Mfs`Mfs`"]


MAD8Survey::usage = "MAD8Survey.m is a package that provides a function to deal with the MAD Version 8 SURVEY file."


surveyTapeRead::usage = "surveyTapeRead[\"filename\"] returns an mfs data object containing all the information from a MAD8 SURVEY output file."


MAD8Survey::badarg = "You called `1` with argument `2`!"


Begin["`Private`"]


surveyTapeRead[fn_String]:=
Module[
{str,ans,rawFile,header,trailer,colheads={"KEYWORD","NAME","L","ANGLE","K1","K2","TILT","E1","E2","H1","H2","X","Y","Z","SUML","THETA","PHI","PSI"}
},
rawFile=ReadList[fn,Record];
If[rawFile===$Failed,rawFile,
header=Take[rawFile,2];
rawFile=Drop[rawFile,2];
rawFile=If[StringLength[#]>80,StringTake[#,80],#]&
/@rawFile;
rawFile=StringJoin/@Partition[rawFile,4];
rawFile=
(Flatten[{
StringTake[#1,4],
ans=ReadList[str=StringToStream[StringDrop[#1,4]],{Word,Table[Number,{16}]}];Close[str];ans}
]&)/@rawFile;
mfs[{
{"HEADER",header},
{"COMMENT","mfs data object created from MAD Version 8 tape file format."},{"FILE",fn}
},
colheads,
rawFile
]
]
]


End[ ]


Protect[surveyTapeRead]


EndPackage[ ]



