(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



Clear[RING]


basedir="c:\\mad2\\lc\\dr\\rdr2\\";


ReadInMADFile[basedir<>"rdr2.mff"];


SPLITRING=RotateLeft[Select[ExpandLattice[RING],#[[3]]>0&],1];


RING=(MADFlatten[If[Length[#]>=2&&(#[[1,2]]==="Quadrupole"||#[[1,2]]==="Sextupole")&&Union[#]==={#[[1]]},ReplacePart[#[[1]],Length[#]*#[[1,3]],3],#]&/@Split[MADFlatten[SPLITRING]]]);



